### ISSUE TITLE
Type definition file does not correspond to current code

### ISSUE THREAD

**Issue by vgoloviznin** [emailable/emailable-node#15]
Hey!

It looks like the type definition file (https://github.com/emailable/emailable-node/blob/master/lib/emailable.d.ts) was not updated with the code update, which leads to issues when using in TS environment.

**Comment by jclusso** [comment]
Can you elaborate? Also have you seen [this issue](https://github.com/emailable/emailable-node/pull/12)?

**Comment by vgoloviznin** [comment]
By default the `Emailable` class is exported in the module: https://github.com/emailable/emailable-node/blob/master/lib/emailable.d.ts#L27, however the real code exports a function that creates an instance of this class: https://github.com/emailable/emailable-node/blob/master/lib/emailable.js#L23

**Comment by jclusso** [comment]
To be honest, we don't use TS internally and only added TS definitions to make the library compliant. This sounds like a rather simple fix if I'm understanding correctly. Do you know how the definition should be adjusted? If so a PR would be great, or just posting it here is fine too and we'll get it sorted out.

**Comment by vgoloviznin** [comment]
Sure, I'll make a PR with a proper declaration
