### ISSUE TITLE
Not able to add optional params for batch verify and status

### ISSUE THREAD

**Issue by mgiatti** [emailable/emailable-node#3]
I am checking https://emailable.com/docs/api?shell#get-the-status-of-a-batch and in the documentation it says that we can pass some aditional params for most of cases for test purposes. However,. checking the code the Batch class cannot add optional params like "simulate" or "partial"

**Comment by jclusso** [comment]
@mgiatti sorry about this. This library hasn't been updated to support this yet. We'll work on getting these options added.

**Comment by jclusso** [comment]
@mgiatti this has been added in [2.1.0](https://github.com/emailable/emailable-node/releases/tag/2.1.0).
